CREATE TABLE User (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  phone VARCHAR(255),
  email VARCHAR(255),
  description TEXT,
  registerDate DATE
);

CREATE TABLE Student (
  id INTEGER PRIMARY KEY REFERENCES User(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  matric VARCHAR(255) NOT NULL
);

CREATE TABLE Employer (
  id INTEGER PRIMARY KEY REFERENCES User(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE Company (
  id INTEGER PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255),
  email VARCHAR(255),
  description TEXT,
  registerDate DATE
);

CREATE TABLE CompanyContact (
  id INTEGER PRIMARY KEY,
  company_id INTEGER REFERENCES Company(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  employer_id INTEGER REFERENCES Employer(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE Job (
  id INTEGER PRIMARY KEY,
  company_id INTEGER,
  title VARCHAR(255) ,
  description TEXT,
  status INTEGER,
  salary INTEGER,
  applicationDeadline DATE,
  deadline DATE,
  FOREIGN KEY (company_id) REFERENCES Company(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE Interest (
  id INTEGER PRIMARY KEY,
  student_id INTEGER,
  job_id INTEGER,
  status INTEGER,
  FOREIGN KEY (student_id) REFERENCES Student(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  FOREIGN KEY (job_id) REFERENCES Job(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);